### ISSUE TITLE
Add a comma after "... , for example,"

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-hapi#138]
https://github.com/OCHA-DAP/hdx-hapi/blob/4b5e413a59fa3d3c89787924989f6360e1200fbb/hdx_hapi/config/doc_snippets.py#L32

**Comment by IanHopkinson** [comment]
Fixed in https://github.com/OCHA-DAP/hdx-hapi/pull/151/commits/d862edce02f99490ea0541e19325415d60cb9a79
