### ISSUE TITLE
Change to "Operational Presence"

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-hapi#139]
https://github.com/OCHA-DAP/hdx-hapi/blob/4b5e413a59fa3d3c89787924989f6360e1200fbb/docs/subcategory_details.md?plain=1#L52

![image](https://github.com/OCHA-DAP/hdx-hapi/assets/1654485/63af4b7f-72e4-457b-9fd2-5b2f85f8275d)

**Comment by turnerm** [comment]
Fixed in the latest version
