### ISSUE TITLE
Remove period to make consistent with others

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-hapi#144]
https://github.com/OCHA-DAP/hdx-hapi/blob/25f87356f502c551cd810ed6be02e3f7b61ebf20/hdx_hapi/endpoints/get_operational_presence.py#L45

**Comment by IanHopkinson** [comment]
Fixed in https://github.com/OCHA-DAP/hdx-hapi/pull/151/commits/d862edce02f99490ea0541e19325415d60cb9a79
