### ISSUE TITLE
Add newline or a space after the previous sentence

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-hapi#148]
https://github.com/OCHA-DAP/hdx-hapi/blob/25f87356f502c551cd810ed6be02e3f7b61ebf20/hdx_hapi/endpoints/get_affected_people.py#L140

This line occurs on most of the endpoints and is appearing like this:

<img width="592" alt="image" src="https://github.com/OCHA-DAP/hdx-hapi/assets/1654485/9c44fc34-8ee6-4122-a87f-e55c7157a36b">

As part of this ticket, please fix this one, but also all other occurrences

**Comment by cjhendrix** [comment]
I think this is only happening in `/refugees` and `/humanitarian-needs`

**Comment by IanHopkinson** [comment]
Fixed in https://github.com/OCHA-DAP/hdx-hapi/pull/151/commits/d862edce02f99490ea0541e19325415d60cb9a79
