### ISSUE TITLE
tweak to /sector description

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-hapi#166]
https://github.com/OCHA-DAP/hdx-hapi/blob/3ad05b40409a2fc8a2662d044f715acc5517e9ba/hdx_hapi/endpoints/get_humanitarian_response.py#L137

Please edit this para to:
`There are a variety of standards for the naming of humanitarian sectors. The codes and descriptions used in HDX HAPI are based on <a href="https://data.humdata.org/organization/54255d0b-c6b1-4517-9722-17321f6634ab">this dataset</a>.`

**Comment by IanHopkinson** [comment]
Fixed in https://github.com/OCHA-DAP/hdx-hapi/pull/171
