### ISSUE TITLE
wrong parameter description in /wfp-market

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-hapi#168]
https://github.com/OCHA-DAP/hdx-hapi/blob/34a6cc9aabd6acd9c859c0ed74dafcac0d93904d/hdx_hapi/endpoints/get_wfp_market.py#L56

The descriptions should be:

`...unique code identifying the market`
and
`Filter the response by the name of the market`

**Comment by IanHopkinson** [comment]
Fixed in https://github.com/OCHA-DAP/hdx-hapi/pull/171
