### ISSUE TITLE
change snippet for admin reference numbers

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-hapi#169]
https://github.com/OCHA-DAP/hdx-hapi/blob/34a6cc9aabd6acd9c859c0ed74dafcac0d93904d/hdx_hapi/config/doc_snippets.py#L13

Change two lines here to read:
`Filter the response by the 1st subnational administrative division reference number.`
and
`Filter the response by the 2nd subnational administrative division reference number.`

**Comment by IanHopkinson** [comment]
Fixed in https://github.com/OCHA-DAP/hdx-hapi/pull/171
